apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p1abzn7cl-python
  janus-idp.io/tekton: p1abzn7cl-python
  backstage.io/kubernetes-id: p1abzn7cl-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p1abzn7cl-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
